resources:
  'entity:breakpoint': 'entity:breakpoint'
  'entity:breakpoint_group': 'entity:breakpoint_group'
  'entity:comment': 'entity:comment'
  'entity:node': 'entity:node'
  'entity:entity_display': 'entity:entity_display'
  'entity:file': 'entity:file'
  'entity:taxonomy_term': 'entity:taxonomy_term'
  'entity:user': 'entity:user'
  'entity:view': 'entity:view'
  dblog: dblog
